# Generated by Django 5.1.5 on 2025-01-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectronicsRetailNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название звена сети",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите электронный адрес",
                        max_length=254,
                        unique=True,
                        verbose_name="Электронный адрес",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Введите название страны",
                        max_length=20,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Введите название города",
                        max_length=20,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Введите название улицы",
                        max_length=30,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "home_number",
                    models.CharField(
                        help_text="Введите название номер дома",
                        max_length=10,
                        verbose_name="Номер дома",
                    ),
                ),
                (
                    "debt",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Задолженность перед поставщиком, руб",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "node_level",
                    models.CharField(
                        choices=[("2", "two"), ("0", "zero"), ("1", "one")],
                        default="0",
                        max_length=4,
                        verbose_name="Уровень иерархии",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[("2", "two"), ("0", "zero"), ("1", "one")],
                        default="plant",
                        max_length=20,
                        verbose_name="Тип звена цепи",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nodes.electronicsretailnode",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект сети",
                "verbose_name_plural": "Объекты сети",
            },
        ),
    ]
