# Generated by Django 5.1.5 on 2025-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_level",
            field=models.CharField(
                choices=[("two", "2"), ("one", "1"), ("zero", "0")],
                default="zero",
                max_length=4,
                verbose_name="Уровень иерархии",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("retail", "розничная сеть"),
                    ("plant", "завод"),
                    ("IE", "ИП"),
                ],
                default="plant",
                max_length=20,
                verbose_name="Тип звена цепи",
            ),
        ),
    ]
