# Generated by Django 5.1.5 on 2025-01-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_alter_electronicsretailnode_node_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_level",
            field=models.CharField(
                choices=[("0", "0"), ("1", "1"), ("2", "2")],
                default="zero",
                max_length=4,
                verbose_name="Уровень иерархии",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("завод", "завод"),
                    ("ИП", "ИП"),
                    ("розничная сеть", "розничная сеть"),
                ],
                default="plant",
                max_length=20,
                verbose_name="Тип звена цепи",
            ),
        ),
    ]
