# Generated by Django 5.1.5 on 2025-01-19 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0003_alter_electronicsretailnode_node_level_and_more"),
        ("products", "0002_product_owner_product_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="electronicsretailnode",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_level",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2)],
                default=0,
                verbose_name="Уровень иерархии",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_type",
            field=models.CharField(
                choices=[("n_w", "розничная сеть"), ("f", "завод"), ("IE", "ИП")],
                default="f",
                max_length=20,
                verbose_name="Тип звена цепи",
            ),
        ),
        migrations.RemoveField(
            model_name="electronicsretailnode",
            name="products",
        ),
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="supplier",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nodes.electronicsretailnode",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="electronicsretailnode",
            name="products",
            field=models.ManyToManyField(
                blank=True, null=True, to="products.product", verbose_name="Продукты"
            ),
        ),
    ]
