# Generated by Django 5.1.5 on 2025-01-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_electronicsretailnode_owner_and_more"),
        ("products", "0002_product_owner_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_type",
            field=models.CharField(
                choices=[("f", "завод"), ("n_w", "розничная сеть"), ("IE", "ИП")],
                default="f",
                max_length=20,
                verbose_name="Тип звена цепи",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="products",
            field=models.ManyToManyField(
                to="products.product", verbose_name="Продукты"
            ),
        ),
    ]
