# Generated by Django 5.1.5 on 2025-01-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0005_alter_electronicsretailnode_node_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_type",
            field=models.CharField(
                choices=[("n_w", "розничная сеть"), ("f", "завод"), ("IE", "ИП")],
                default="f",
                max_length=20,
                verbose_name="Тип звена цепи",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nodes.electronicsretailnode",
                verbose_name="Поставщик",
            ),
        ),
    ]
