# Generated by Django 5.1.5 on 2025-01-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0006_alter_electronicsretailnode_node_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="debt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Задолженность перед поставщиком, руб",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_type",
            field=models.CharField(
                choices=[("IE", "ИП"), ("f", "завод"), ("n_w", "розничная сеть")],
                default="f",
                max_length=20,
                verbose_name="Тип звена цепи",
            ),
        ),
    ]
