# Generated by Django 5.1.5 on 2025-01-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0007_alter_electronicsretailnode_debt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electronicsretailnode",
            options={
                "ordering": ["id"],
                "verbose_name": "Объект сети",
                "verbose_name_plural": "Объекты сети",
            },
        ),
        migrations.AlterField(
            model_name="electronicsretailnode",
            name="node_type",
            field=models.CharField(
                choices=[("f", "завод"), ("n_w", "розничная сеть"), ("IE", "ИП")],
                default="f",
                max_length=20,
                verbose_name="Тип звена цепи",
            ),
        ),
    ]
