# Generated by Django 5.1.5 on 2025-01-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название продукта",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Введите название модели продукта",
                        max_length=150,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "release_data",
                    models.DateField(
                        help_text="Введите дату выхода продукта на рынок",
                        max_length=150,
                        verbose_name="Дата выхода продукта на рынок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
